export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const SET_CURRENCY = 'SET_CURRENCY';
export const GET_CURRENCY = 'GET_CURRENCY';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'ADD_PRODUCT_FROM_CART';
export const INCREASE_CART_PRODUCT_AMOUNT = 'INCREASE_CART_PRODUCT_AMOUNT';
export const DECREASE_CART_PRODUCT_AMOUNT = 'DECREASE_CART_PRODUCT_AMOUNT';
